name: Erlang CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:


permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:latest

    steps:
    - uses: actions/checkout@v4
    - name: Compile
      run: rebar3 compile
    - name: Run tests
      run: rebar3 eunit
